### ISSUE TITLE
"sqldiff -a" fails with ImportError

### ISSUE THREAD

**Issue by hobbsd** [django-extensions/django-extensions#576]
Using Django 1.4.15 and django-extensions 1.4.5, I get:

```
File "C:\Users\****\py_envs\****\lib\site-packages\django_extensions\management\commands\sqldiff.py", line 31, in <module>
    from django.core.management.base import OutputWrapper
ImportError: cannot import name OutputWrapper
```

For me, sqldiff last worked with version 1.3.9.
