### ISSUE TITLE
shell_plus not working with IPython 0.11

### ISSUE THREAD

**Issue by TvrtkoM** [django-extensions/django-extensions#134]
```
python manage.py shell_plus
```

outputs this:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/home/tvrtko/virtualenvs/satchmoenv/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 88, in handle_noargs
    shell = IPython.Shell.IPShell(argv=[], user_ns=imported_objects)
AttributeError: 'module' object has no attribute 'Shell'
```

if IPython version 0.11 is installed.
