### PR TITLE
Remove `generate_password` command

### LINKED ISSUE #1897: ./manage.py generate_password raises an AttributeError: 'BaseUserManager' object has no attribute 'make_random_password'
The `generate_password` command stopped working in django 5.1. It raises an error now:
```
...
  File "proj/venv/lib/python3.10/site-packages/django_extensions/management/commands/generate_password.py", line 30, in handle
    return manager.make_random_password()
AttributeError: 'BaseUserManager' object has no attribute 'make_random_password'
```

### PR DESCRIPTION
**Pull request by browniebroke**
As per https://github.com/django-extensions/django-extensions/pull/1900#issuecomment-2568027272 the underlying code has been removed from Django, because it didn't work reliably.

Fix #1897

### CODE REVIEW

**Comment by trbs** [comment]
For now, I changed the `generate_password` command to use Python's `secret' module.
Would love to have your feedback on that.

**Comment by browniebroke** [comment]
Nice idea! Will close this 👍🏻
