### PR TITLE
Fix AttributeError in pipchecker command

### LINKED ISSUE #1004: AttributeError: 'Command' object has no attribute '_is_stable'
Pipchecker has been broken in commit 5ad36e6d9ed585b98cf3964f83fe80ad65a6913b/PR #978

### PR DESCRIPTION
**Pull request by federicobond**
Fixes #1004

### CODE REVIEW

**Comment by trbs** [comment]
please fix the flake8 errors. thanks

**Comment by trbs** [comment]
Thanks !
