### ISSUE TITLE
AttributeError: 'Command' object has no attribute '_is_stable'

### ISSUE THREAD

**Issue by michael-k** [django-extensions/django-extensions#1004]
Pipchecker has been broken in commit 5ad36e6d9ed585b98cf3964f83fe80ad65a6913b/PR #978

**Comment by federicobond** [comment]
I am terribly sorry. I must have done a bad merge when passing over the changes from the code I was using. I will submit a fix shortly.
