### ISSUE TITLE
'ForeignKey' object has no attribute 'remote_field on Dango 1.8

### ISSUE THREAD

**Issue by sillyfatcat** [django-extensions/django-extensions#1407]
For business reasons we're stuck with using django 1.8 and django-extensions 2.2.1 but we're running into this:

command: `./manage.py graph_models -a -g -o my_project_visualized.png`

```    t += " ({0})".format(field.remote_field.field_name)
AttributeError: 'ForeignKey' object has no attribute 'remote_field'
```

**Comment by trbs** [comment]
Yeah, your right, this broke with an upgrade to newer Django versions... Django-Extensions follows the same support schema as Django so "officially" support ended in April 2018...

If there is an easy, something which does not really add code complexity or maintenance burden, PR possible which makes it work on Django 1.8 then I am not against merging it.

However to be honest we cannot guarantee that this in turn will not be removed again sometime in the future....

There will probably be more and more issues over time as the code base will not test or check for compatibility on those older non supported Django version and sometimes will actively remove compatibility code in favor of easier maintenance.

I realize this might not be entirely the answer you are looking for but I hope it helps none the less :-) 

If there is a clean none intrusive patch possible then please submit a PR for inclusion.
