### ISSUE TITLE
graph_models error with pydot lastest version

### ISSUE THREAD

**Issue by Eric-Bujeque** [django-extensions/django-extensions#927]
I'm working with python 2.7.11+ and latest version of pydot (1.2.2) and pyparsing (2.1.5). When I run:

`django-admin graph_models -o models.png`

I get:

`Traceback (most recent call last):
  File "/home/ebujeque/.virtualenvs/gmp/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django_extensions/management/commands/graph_models.py", line 164, in handle
    self.render_output_pydot(dotdata, **options)
  File "/home/ebujeque/.virtualenvs/gmp/local/lib/python2.7/site-packages/django_extensions/management/commands/graph_models.py", line 221, in render_output_pydot
    graph.write(output_file, format=format)
AttributeError: 'list' object has no attribute 'write'`

I tried with pyparsing(1.5.7) and pydot(1.2.2), but it fails too. I solved it with:
- pyparsing==1.5.7
- pydot=1.1.0

But It can't work with lastest version of both libraries.

**Comment by x007007007** [comment]
me too, I 'm working on python3.5

**Comment by vhdmsm** [comment]
And me too.

**Comment by trbs** [comment]
Please check with the github version which has @x007007007 PR was merged

**Comment by trbs** [comment]
Please reopen / create a new ticket if there still issues.

**Comment by Jufik** [comment]
Same here, using pydot 1.2.3

It looks like there's been a change in Pydot used to return an object, it now gives an array.
I'll try to contribute, here is a quick fix, on file 

> env/lib/python2.7/site-packages/django_extensions/management/commands/graph_models.py
line 212, make
`graph = pydot.graph_from_dot_data(dotdata)`
become
`graph = pydot.graph_from_dot_data(dotdata)[0]`

**Comment by trbs** [comment]
sorry, i see this hasn't made it into a release yet :(

hope to have a new release out soon !

**Comment by JamesPeabody** [comment]
I'm having the same problem but it appears that the line that needs an edit is 141 rather than 212.

I'm not sure what the difference is, or why my milage differs, but the above edit as provided by Jufik did the trick.

**Comment by trbs** [comment]
@JamesPeabody are you sure ? Line 141 is a blank line it seems: https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/graph_models.py#L141

**Comment by JamesPeabody** [comment]
The three of us are looking at different versions of the code. For the link you provided, the line appears to be 214. However, that would need to be tested.

**Comment by trbs** [comment]
On line 220 of the latest version https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/graph_models.py#L220 the above patch/fix is already incorporated.
