### PR TITLE
Fix UniqFieldMixin for CheckConstraint compatibility for Django 2.2+

### LINKED ISSUE #1522: RandomCharField (UniqueFieldMixin) not compatible with model with CheckConstraint
Hello,

I'm using django `Django==2.2.9`

I have a model with a `RandomCharField` and some extra constraint defined. 

```python

class MyModel(RandomSlugModel, TimeStampedModel):
    class Meta:
        unique_together = (("remote_field", "user"),)
        constraints = [
            CheckConstraint(
                check=Q(units_sold__lte=F('units_in_item')), name='check_sold',
            ),
            CheckConstraint(
                check=Q(units_reserved__lte=F('units_in_item')), name='check_reserved',
            ),
        ]
    [...]
```

If I try to save I get the following stack trace : 

```
web_1          |   File "/usr/local/lib/python3.8/site-packages/django_extensions/db/models.py", line 23, in save
web_1          |     super(TimeStampedModel, self).save(**kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
web_1          |     self.save_base(using=using, force_insert=force_insert,
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 777, in save_base
web_1          |     updated = self._save_table(
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 870, in _save_table
web_1          |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 907, in _do_insert
web_1          |     return manager._insert([self], fields=fields, return_id=update_pk,
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
web_1          |     return query.get_compiler(using=using).execute_sql(return_id)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1367, in execute_sql
web_1          |     for sql, params in self.as_sql():
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1309, in as_sql
web_1          |     value_rows = [
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1310, in <listcomp>
web_1          |     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1310, in <listcomp>
web_1          |     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1261, in pre_save_val
web_1          |     return field.pre_save(obj, add=True)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django_extensions/db/fields/__init__.py", line 387, in pre_save
web_1          |     return self.find_unique(
web_1          |   File "/usr/local/lib/python3.8/site-packages/django_extensions/db/fields/__init__.py", line 74, in find_unique
web_1          |     if self.attname in constraint.fields:
web_1          | AttributeError: 'CheckConstraint' object has no attribute 'fields'
```

By reading the code at the pointed error ( https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/fields/__init__.py#L74 ) 
I would say it should be changed to : 
`               if self.attname in constraint.fields:`
to
`               if hasattr(constraint, 'fields') and self.attname in constraint.fields:`

It would help to support all type of constraint and not only the `UniqueConstraint` one : I think that constraint should be any of `BaseConstraint` that doesn't define a fields attribute.

Let me know if you need more details or would like a pull request with the suggested change above.
 
_In the meanwhile for those having the same issue a temporary workaround is to define a dummy class that wrap your constraint (in my case the CheckConstraint) and define a fields attribute._

### PR DESCRIPTION
**Pull request by radekwlsk**
This PR fixes logic of `UniqFieldMixin` to work with Django 2.2+ `django.db.models.Model.Meta.constraints` that have not only instances of `UniqueConstraint` but also `CheckConstraint`.

Closes #1522

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !
