### ISSUE TITLE
./manage.py generate_password raises an AttributeError: 'BaseUserManager' object has no attribute 'make_random_password'

### ISSUE THREAD

**Issue by fnceba** [django-extensions/django-extensions#1897]
The `generate_password` command stopped working in django 5.1. It raises an error now:
```
...
  File "proj/venv/lib/python3.10/site-packages/django_extensions/management/commands/generate_password.py", line 30, in handle
    return manager.make_random_password()
AttributeError: 'BaseUserManager' object has no attribute 'make_random_password'
```

**Comment by deronnax** [comment]
It was removed in 5.1 https://docs.djangoproject.com/en/5.1/releases/5.1/#features-removed-in-5-1

**Comment by browniebroke** [comment]
Yes. I think it has been deprecated for a few versions so I replaced it by calling the function directly: https://github.com/django-extensions/django-extensions/pull/1900

**Comment by browniebroke** [comment]
Quoting this suggestion from the PR:

> regarding the PR itself, are we sure we want to reintroduce something django removed ?
> 
> EDIT: original rational in https://code.djangoproject.com/ticket/33758
> 
> > The usage of
> > User.objects.make_random_password()
> > is limited since the generated passwords are not valid because they were created without meeting the validators criteria.

@fnceba do you have a strong use-case for this command or you were just trying it out? What would be the impact if it was removed from django-extensions?

**Comment by fnceba** [comment]
@browniebroke
For me this command is not vital, I think it's ok to remove it.
Yeah, I just was trying this command out and noticed an error.

**Comment by deronnax** [comment]
can probably be closed now, since https://github.com/django-extensions/django-extensions/commit/2066b1fe516ef30e901ac9b7e45e9a2ff07c8176
