### ISSUE TITLE
"mail_debug" doesn't work with django 1.10

### ISSUE THREAD

**Issue by dethos** [django-extensions/django-extensions#947]
The management command `mail_debug` no longer works on Django 1.10. Possibly due to the following change:

> Support for optparse is dropped for custom management commands.

When I try to run it, I get the following error message:
```
File "manage.py", line 14, in <module>
  execute_from_command_line(sys.argv)
...
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by dethos** [comment]
My mistake, I was using an outdated version of this package. Will close the issue.
